version: '3.4'

services:
  eurekaclient:
    image: ${DOCKER_REGISTRY-}eurekaclient
    build:
      context: .
      dockerfile: EurekaClient/Dockerfile
    ports:
      - "8080:8080"
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "8081:8081"
  movieservice:
    image: ${DOCKER_REGISTRY-}movieservice
    build:
      context: .
      dockerfile: MovieService/Dockerfile
    ports:
      - "8082:8082"
  reviewservice:
    image: ${DOCKER_REGISTRY-}reviewservice
    build:
      context: .
      dockerfile: ReviewService/Dockerfile
    ports:
      - "8083:8083"